app: # 应用基本配置
  env: Dev # 环境名称  Pro
  port: 9000 # 服务监听端口号
  app_name: orderingsystem # 应用名称
  app_url: http://localhost # 应用域名
log:
  root_dir: ./storage/logs # 日志根目录
  infolog: info.log
  errorlog: error.log 
  errorinfolog: errorinfo.log
  ordererrorinfolog: ordererrorinfo.log
  format: console  # 写入格式 可选json（方便日后调用使用脚本操作）
  show_line: true # 是否显示调用行
  max_backups: 2 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩
database:
  driver: mysql # 数据库驱动
  host: localhost  # 域名
  port: 3306 # 端口号
  database: videosystem # 数据库名称
  username: root # 用户名     go env -w GOOS=
  password: Admin123.   # 密码  aliuyun Admin123.
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称
jwt:
  secret: KZDTTpQtjloOtaHwwmI1fpOvGh2HUPuJYZlSX
  jwt_ttl: 10800
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800
redis:
  host: localhost
  port: 6379
  db: 0 
  password: