app:
  env: dev
  port: 17999
  appname: orderService
databases:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: Admin123.
  dbname: videosystemdev
  charset: utf8mb4
  maxIdleConns: 20
  maxOpenConns: 100
redis:
  host: 127.0.0.1
  port: 6379
rabbitmq:
  host: 127.0.0.1
  port: 5672
  vhost: /videosystemdev
  user: adminroot
  password: adminroot
  exchangename: orderservice_topic
  infoqueue: orderinfoqueue  # 订单服务日志服务info队列名
  errorqueue: ordererrorqueue  # 订单日志服务error队列名
  flasheventreqqueue: flasheventreqqueue  # 订单服务-秒杀-请求保存队列名
  flasheventreqbackupqueue: flasheventreqbackupqueue  # 订单服务-秒杀-请求保存备份队列名
  flasheventresqueue: flasheventresqueue  # 订单服务-秒杀-结果保存队列名
  flasheventreadypayqueue: flasheventreadypayqueue  # 订单服务-秒杀-待支付订单队列
  flasheventpayresqueue: flasheventpayresqueue  # 订单服务-秒杀-支付成功订单队列
dealexchangeconfig:  # 这里是手动将消息发送到死信队列的配置，按需使用
  deadexchange: dealexchange_topic   # 死信队列交换机
  dealdefalutqueue: dealqueue        # 默认绑定死信交换机的队列
  routingkey: dlx.routing.default    # 默认队列绑定默认路由键
locallogs:
  dir: ./logs
  logfilename: /locallogs.log
  max_backups: 3
  max_size: 100
  max_age: 30
  isJson: true
  compress: true
  defaultLevel: info
websocket:
  maxdur: 180
  handshaketimeout: 5
  enablecompression: true
  jwtsecretkey: tb4hn_E72w9m0TKEDf4jSd8P5aW2x3XQAvVzE4w6Bis=