app:
  env: dev
  port: 17999
  appname: orderService
databases:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: Admin123.
  dbname: videosystemdev
  charset: utf8mb4
  maxIdleConns: 20
  maxOpenConns: 100
redis:
  host: 127.0.0.1
  port: 6379
rabbitmq:
  host: 127.0.0.1
  port: 5672
  vhost: /videosystemdev
  user: adminroot
  password: adminroot
  exchangename: orderservice_topic
  infoqueue: orderinfoqueue  # 服务info队列名
  errorqueue: ordererrorqueue  # 服务error队列名
locallogs:
  dir: ./logs
  logfilename: /locallogs.log
  max_backups: 3
  max_size: 100
  max_age: 30
  isJson: true
  compress: true
  defaultLevel: info
websocket:
  maxdur: 180
  handshaketimeout: 5
  enablecompression: true
  jwtsecretkey: tb4hn_E72w9m0TKEDf4jSd8P5aW2x3XQAvVzE4w6Bis=

  
  
