app:        # 服务基本设置
  env: dev  
  servicename: logService
rabbitmq:
  host: 127.0.0.1
  port: 5672
  vhost: /videosystemdev
  user: adminroot
  password: adminroot
  userexchange: userServiceLog_topic   # 用户服务交换机
  userinfoqueue: userinfoqueue  # 用户服务info队列名
  usererrorqueue: usererrorqueue  # 用户服务error队列名
usermanagerconfig:
  serivcename: userService  # 服务名称
  userexchange: userServiceLog_topic   # 服务交换机
  userinfoqueue: userinfoqueue  # 用户服务info队列名
  usererrorqueue: usererrorqueue  # 用户服务error队列名
authserverconfig:
  serivcename: authenticationService  # 服务名称
  authexchange: authservice_topic   # 服务交换机
  authinfoqueue: authinfoqueue  # 用户服务info队列名
  autherrorqueue: autherrorqueue  # 用户服务error队列名
productserverconfig:
  serivcename: productService  # 服务名称
  authexchange: productservice_topic   # 服务交换机
  authinfoqueue: productinfoqueue  # 服务info队列名
  autherrorqueue: producterrorqueue  # 服务error队列名
orderserverconfig:
  serivcename: orderService  # 服务名称
  authexchange: orderservice_topic   # 服务交换机
  authinfoqueue: orderinfoqueue  # 服务info队列名
  autherrorqueue: ordererrorqueue  # 服务error队列名
dealexchangeconfig:
  deadexchange: dealexchange_topic   # 死信队列交换机
  dealdefalutqueue: dealqueue        # 默认绑定死信交换机的队列
  routingkey: dlx.routing.default    # 默认队列绑定默认路由键
baselogconfig:  # 日志基本设置
  root_dir: ./storage
  show_line: true
  max_backups: 3
  max_size: 100
  max_age: 30
  compress: true
  defaultErrorL: error
localserverlog:
  servicename: localService
  root_dir: /Logservice
  level: info
  jsonformat: true
  info: /logserviceInfo.log
  error: /logserviceError.log
userservicelog: # 本地存储配置
  servicename: userService
  root_dir: /UserService
  level: info
  jsonformat: true
  info: /userserviceInfo.log
  error: /userserviceError.log
authsvicelog:  # 本地存储配置
  servicename: authenticationService
  root_dir: /AuthService
  level: info
  jsonformat: true
  info: /AuthserviceInfo.log
  error: /AuthserviceError.log
productservicelog:  # 本地存储配置
  servicename: productService
  root_dir: /ProductService
  level: info
  jsonformat: true
  info: /ProductserviceInfo.log
  error: /ProductserviceError.log
orderservicelog:  # 本地存储配置
  servicename: orderService
  root_dir: /OrderService
  level: info
  jsonformat: true
  info: /OrderserviceInfo.log
  error: /OrderserviceError.log
