app:  # 这里是服务发现配置
  env: dev
  port: 9999
  appname: authenticationService
redis:
  host: 127.0.0.1
  port: 6379
  db: 1
rabbitmq:
  host: 127.0.0.1
  port: 5672
  vhost: /videosystemdev
  user: adminroot
  password: adminroot
rabbitmqlog:  # 这里表示日志相关的配置，后续可能会有请求相关的配置作为限流
  exchangename: authservice_topic
  userinfoqueue: authinfoqueue  # 认证服务info队列名
  usererrorqueue: autherrorqueue  # 认证服务error队列名
locallogs:
  dir: ./logs
  logfilename: /locallogs.log
  max_backups: 3
  max_size: 100
  max_age: 30
  isJson: true
  compress: true
  defaultLevel: info
userserviceapi:
  name: userService
  timeout: 5
  baseurl: http://127.0.0.1:19999
  clientpath: /consumer      # 对外客户端分组路由名称
  adminpath: /management     # 对外管理端分组路由名称
  client:
    login: /user/loginbypvc   # 用户服务实际路径
    register: /user/register 
    getverifcode: /user/getvarifcode
    getuserinfo: /user/getuserinfo
    inproveinfo: /user/inproveinfo
  admin: 
    login: ""
jwt:
  secretkey: tb4hn_E72w9m0TKEDf4jSd8P5aW2x3XQAvVzE4w6Bis=
  jwttil: 300

# rateLimiting:    # 请求速率限制 -- DB & redis & config
# requestPeaking:  # 请求峰值限制 -- MQ & config
# errorHandling:   # 错误处理机制
# userservice: